### ISSUE TITLE
Update Converts By Adding Latest Pandoc

### ISSUE THREAD

**Issue by jhomme** [EmpowermentZone/EdSharp#27]
Hi,
GitHub will not allow me to upload pandoc.exe. It is too large. I am proposing creating an ini file key and variable for the Pandoc path on the user's system, so that no matter what version of Pandoc the user has, EdSharp will use it. The drawback of this is that EdSarp would not come with PanDoc. I could try to put in a way to direct the user to get PanDoc, tel EdSharp the path, or whatever. If anyone has ideas, please comment.

**Comment by frastlin** [comment]
Can we add it in the installer, so when the user installs EdSharp, it looks for pandoc and if there is no pandoc, then it installs pandoc.

**Comment by frastlin** [comment]
You can add pandoc in a release, but not on the repo here.

**Comment by jhomme** [comment]
hi Brandon,

What does that mean?

Thanks.

Jim

On Nov 17, 2018, at 1:40 PM, Brandon <notifications@github.com> wrote:

You can add pandoc in a release, but not on the repo here.

**Comment by jhomme** [comment]
hi Brandon,

I will look into this. This sounds like something to try.

Gym

On Nov 17, 2018, at 1:40 PM, Brandon <notifications@github.com> wrote:

Can we add it in the installer, so when the user installs EdSharp, it looks for pandoc and if there is no pandoc, then it installs pandoc.

**Comment by frastlin** [comment]
If you go to:
[releases](https://github.com/EmpowermentZone/EdSharp/releases)
and click new release, you can upload a binary file that is up to 2 GB. If we want something larger, we need to go to the github storage system (that we can look at if we need).

The code repo can only be up to 1 GB and you can't have files over 100 MB. The code repo is for code and the release is for something users download to run the code, so there are different file size limits.
