### ISSUE TITLE
Please include NVDA screen reader

### ISSUE THREAD

**Issue by gregjozk** [EmpowermentZone/EdSharp#3]
Because, popularity of NVDA is grawing rapidly, it could useful if it would be included in program like other screen reader such as jaws, window-eyes and others.

**Comment by frastlin** [comment]
Hello,
NVDA works perfectly well with EdSharp. It is just not mentioned in the readme for some reason. I'll see about adding it.

**Comment by frastlin** [comment]
I have added NVDA to the Readme. If there are specific things you would like NVDA to do in EdSharp, open another issue.
Thanks,
